#pragma once
#include "DomNode.h"

namespace xo {

/* This was built to house images such as bitmaps and SVGs

THIS IS NOT USED, and NOT REALLY IMPLEMENTED. Should probably just get rid of it.

I'm still not sure whether we really need a special <img> object, or
if it's sufficient to just use style attributes such as background-img, etc.

Using a dedicated img object seems like it will make it easier to
add special things like HSV filters. But then again, maybe one wants
to enable such things on all types of nodes. Why limit it to images?
*/
class XO_API DomImg : public DomNode {
public:
	DomImg(xo::Doc* doc, xo::InternalID parentID);
	virtual ~DomImg();

	void CloneSlowInto(DomEl& c, uint32_t cloneFlags) const override;

	ImageID GetImageID() const { return ImageID; }

protected:
	xo::ImageID ImageID; // This is an anonymous image ID, automatically generated by ImageStore
};
}
